; PlatformIO Project Configuration File
; Punkt Dominacji Airsoft - ESP32 Firmware

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Biblioteki
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    https://github.com/avishorp/TM1637.git
